from ubuntu
run apt-get update
run apt-get install -y openssh-server python2.7
run mkdir /var/run/sshd
run chmod 0755 /var/run/sshd
add setPassword.py /root/
add startSshServer.sh /root/
run chmod 0755 /root/startSshServer.sh
